### ISSUE TITLE
Javatar removes "Project Src" path from Settings File

### ISSUE THREAD

**Issue by daneb** [spywhere/Javatar#48] opened 2015-07-06 21:29 UTC
Problem: javatar source folder path (entry) is being removed from the settings file illegally

How to Replicate: When my project's main()  is long running or waiting for STDIN, closing the window, then closing the Project, results in a side-affect of the javatar source folder path being removed from the settings file.

Affect: This causes a whole host of issues, one which resulted in me being able to set any dependencies (External Jars) in any project I created. The menu item with the directories after Project -> Dependencies -> External JAR just didn't load. That's harder to reproduce. What isn't is that every time I have to reset the source folder path.

Here is a gist of my configuration before, and then after:
https://gist.github.com/daneb/e51b9c1defdd303f9c13

My environment: 
Sublime 3083
Mac OS 10.10.4

Thanks and please shout if I can assist with further info

Dane Balia

**Comment by spywhere** [comment] 2015-07-07 02:12
I think the problem is you are working so fast! and Javatar cannot keep it up with you. What I means is when you are working with Javatar, Javatar will keep storing the project data to user's settings file which will be used when you restart Sublime Text after close it without saving your project to restore the last project data as it should be consistent with all the things.

A project settings can be lost due to this procedure, when you open the Sublime Text, Javatar will store the project data immediately and every 60 seconds (by default). That is mean if you already open Sublime Text and open your project file (or create a new one), while 60 seconds timeout is not yet reached, you close the Sublime Text causing unsaved project data lost (which means on the "after" part of your gist is what Javatar saved before timeout).

To solve this issue there are 2 ways, the first is to disable automatic project restoration by set `allow_project_restoration` to `false`, the another is to set the timeout (interval rather) faster than 60 seconds using the `project_update_interval` key in the settings file.

If you have further problems please include Javatar action history too, accessed via `Key+Shift+K, Key+Shift+H`.

**Comment by daneb** [comment] 2015-07-07 18:19
Thank you very much for your response and that makes sense.
I think I will go with the project_update_interval key.

**Closed** 2015-07-08 01:29 UTC
Labels: bug

**Comment by daneb** [comment] 2015-07-08 20:26
Hi @spywhere 

Sadly these two options do not work.
I tried them separately and together.
I even dropped it down to 1 second (which it was saving correctly), but upon closing the project (using tail -f) I can see it clear out my "source folder" path.

Thus every time I open the project I have to re-set the "source folder".

There is also some other strangeness where it removed one of my folders as well as inserting an incorrect source folder path from another project (I have no idea how what is happening and trying to replicate).

**Comment by daneb** [comment] 2015-07-08 20:27
The History if you need it.

https://gist.github.com/daneb/cd28aeea24eaea166372
